# Generated by Django 2.2.6 on 2020-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_userlogin_cookie_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='cookie_consent',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
