# Generated by Django 2.2.6 on 2020-12-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20201230_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='password',
        ),
        migrations.AlterModelTable(
            name='userlogin',
            table='user_cookie_consent',
        ),
    ]
